

def selector
  @linksArray = ["http://www.lingscars.com/",
     "http://www.111111111111111111111111111111111111111111111111111111111111.com/",
      "http://www.omfgdogs.com/",
      "http://www.constellation7.org/Constellation-Seven/Josiah/Index.htm",
      "http://www.foxconn.com",
      "https://vi.wikipedia.org/wiki/M%E1%BA%A1t_b%E1%BB%A5i_nh%C3%A0",
      "http://www.warnerbros.com/archive/spacejam/movie/jam.htm",
      "http://toastytech.com/evil/",
      "http://www.3riversstadium.com/index2.html",
      "http://meep.us/",
      "https://www.rigzone.com/search/c/companies/manufacturers_suppliers/general_supplies/rig_replacement_parts/",
      "http://www.ebay.com/itm/like/361395075948?lpid=82&chn=ps&ul_noapp=true",
      "https://www.amazon.com/Eamee-500-CLEAR-False-Toenails/dp/B00272UIPG",
      "https://www.nts.go.kr/eng/about/about_21.asp?top_code=A001&sub_code=AS02&ssub_code=ASB1",
      "http://www.cnn.com/US/OJ/",
      "https://en.wikipedia.org/wiki/Central_Military_Commission_of_the_Workers%27_Party_of_Korea",
      "http://home.mcom.com/home/welcome.html",
      "http://uncyclopedia.wikia.com/wiki/Cabbage",
      "http://www.crazyscarygames.com/images/creepy_dolls/creepy-dolls-ugly-face.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/41sbhmTWuOL.jpg",
      "https://www.google.com/search?q=crucifixion&rlz=1C5CHFA_enUS697US697&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiw2YDajNDNAhWKaT4KHeHSCeYQ_AUICCgB&biw=1265&bih=637#tbm=isch&q=donald+trump",
      "http://www.skyla.com/zh_tw/index.php",
      "http://www.washingtonpost.com/wp-srv/projects/yrreview/year.htm",
      "http://usatoday30.usatoday.com/sports/baseball/sbfant.htm",
      "http://www.arngren.net/",
      "http://www.liteonit.com/terms-of-use.html",
      "http://zombo.com",
      "http://www.ins.tn/",
      "http://topdocumentaryfilms.com/elephant-life-after-death/",
      "http://scaruffi.com/",
      "http://www.tim.org/",
      "http://www.doughney.net/tasty/#meat",
      "http://www.fluffy.com/fluffy/Fluffyhome.html",
      ]

  return @linksArray.sample
end
